import mongoose from "mongoose";

const messageSchema = new mongoose.Schema(
	{
		// Parent chat where this message belongs.
		chatId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "chat",
			required: true,
		},

		// Message text generated by user or AI.
		content: {
			type: String,
			default: "",
			trim: true,
		},

		// Role indicates who sent the message.
		role: {
			type: String,
			required: true,
			enum: ["user", "ai", "system"],
		},
	},
	{
		// Adds createdAt and updatedAt automatically.
		timestamps: true,
	}
);

const messageModel = mongoose.model("Message", messageSchema);

export default messageModel;
